from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.db.database import get_db
import logging

logger = logging.getLogger(__name__)

router = APIRouter()


class CommunicationRequest(BaseModel):
    ticket_id: int
    ticket_title: str
    customer_name: str = "Customer"
    root_cause: str
    recommended_fix: str
    confidence_score: float
    risks: list[str] = []


class CommunicationResponse(BaseModel):
    ticket_id: int
    client_response: str
    redmine_update: str
    closure_comment: str
    follow_up_actions: list[str]
    status: str


def generate_communications(
    ticket_title: str,
    customer_name: str,
    root_cause: str,
    recommended_fix: str,
    confidence_score: float,
    risks: list[str]
) -> dict:
    """Generate professional communications based on analysis"""

    confidence_pct = int(confidence_score * 100)

    client_response = f"""Dear {customer_name},

Thank you for reporting this issue. Our AI-powered investigation team has completed a comprehensive analysis of the reported problem.

**Investigation Summary:**

We have analyzed the ticket, reviewed similar historical issues, and examined related code components. Based on this comprehensive investigation:

**Root Cause:**
{root_cause}

**Recommended Resolution:**
{recommended_fix}

**Investigation Confidence:** {confidence_pct}%

Our engineering team is preparing the fix for this issue and will provide updates on the deployment timeline. We appreciate your patience and will keep you informed of our progress.

If you have any questions or can provide additional information, please don't hesitate to reach out.

Best regards,
Support Engineering Team
Samixa AI Support System"""

    redmine_update = f"""**AI Investigation Complete - Moving to Development**

Investigation Status: Root Cause Identified and Verified

**Root Cause Analysis:**
{root_cause}

**Confidence Level:** {confidence_pct}%

**Recommended Fix:**
{recommended_fix}

**Risk Assessment:**
{chr(10).join([f"- {risk}" for risk in risks]) if risks else "- Minimal risk with proper testing"}

**Next Phase:** Development & Testing

**Action Items:**
1. Technical review of proposed solution
2. Development task creation
3. Implementation planning
4. Comprehensive test plan development
5. Staged deployment planning

**Investigation Timeline:**
- Started: Auto-generated by Samixa AI
- Completed: Just now
- Duration: Real-time analysis

**Notes:** All investigation artifacts and detailed analysis available in Samixa investigation workspace."""

    closure_comment = f"""**Investigation Complete - Ready for Development Phase**

Status: ✅ Root Cause Identified

After comprehensive AI-powered analysis, we have identified the root cause of this issue with **{confidence_pct}% confidence**.

**Root Cause:**
{root_cause}

**Recommended Fix:**
{recommended_fix}

**Risk Mitigation:**
{chr(10).join([f"- {risk}" for risk in risks]) if risks else "- Minimal risk with proper testing on all affected platforms"}

**Development Phase:**
The development team has been provided with detailed investigation findings and will now:
- Create implementation task
- Develop the fix
- Execute comprehensive testing
- Plan staged rollout

**Estimated Timeline:**
- Development: 2-3 business days
- Testing: 1-2 business days
- Staging validation: 1 business day
- Production deployment: 1 business day

**Total ETA: 5-8 business days**

This ticket moves to Development phase. All investigation details are documented in Samixa for future reference and continuous improvement of the platform."""

    follow_up_actions = [
        "Create development task in ticket tracker",
        "Schedule technical review with engineering team",
        "Prepare detailed implementation specification",
        "Define comprehensive test scenarios",
        "Create test automation if applicable",
        "Plan staged rollout strategy",
        "Set up production monitoring alerts",
        "Schedule post-deployment customer validation",
        "Document solution in knowledge base",
        "Schedule retrospective after resolution"
    ]

    return {
        "client": client_response,
        "redmine": redmine_update,
        "closure": closure_comment,
        "actions": follow_up_actions
    }


@router.post("/generate")
async def generate_communication(
    request: CommunicationRequest,
    db: Session = Depends(get_db)
):
    """
    Communication Agent: Generate professional communications

    Generates:
    - Client-facing response (professional, clear, reassuring)
    - Redmine internal update (technical, detailed)
    - Closure comment (summary for next phase)
    - Follow-up actions (clear action items)

    Everything is ready to copy-paste into Redmine or send to customer.

    Uses:
    - Root cause analysis
    - Recommended fix
    - Risk assessment
    - Customer information
    """
    try:
        # Generate communications
        comms = generate_communications(
            request.ticket_title,
            request.customer_name,
            request.root_cause,
            request.recommended_fix,
            request.confidence_score,
            request.risks
        )

        return CommunicationResponse(
            ticket_id=request.ticket_id,
            client_response=comms["client"],
            redmine_update=comms["redmine"],
            closure_comment=comms["closure"],
            follow_up_actions=comms["actions"],
            status="completed"
        )

    except Exception as e:
        logger.error(f"Communication generation failed: {e}")
        return CommunicationResponse(
            ticket_id=request.ticket_id,
            client_response="",
            redmine_update="",
            closure_comment="",
            follow_up_actions=[],
            status="error"
        )
